# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# Asclepias Broker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  app:
    extends:
      file: docker-services.yml
      service: app
  cache:
    extends:
      file: docker-services.yml
      service: cache
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
  kibana:
    extends:
      file: docker-services.yml
      service: kibana
  flower:
    extends:
      file: docker-services.yml
      service: flower
