#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# Asclepias Broker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

CWD=`pwd`
asclepias-broker npm
cd ${VIRTUAL_ENV}/var/instance/static
npm install
cd ${CWD}
asclepias-broker collect -v
asclepias-broker assets build
