#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# Asclepias Broker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

script_path=$(dirname "$0")

export FLASK_ENV=development
# Start Worker and Server
pipenv run celery worker -B -A invenio_app.celery -l INFO& pid_celery=$!

pipenv run invenio run \
       --cert "$script_path"/../docker/nginx/test.crt \
       --key "$script_path"/../docker/nginx/test.key & pid_server=$!

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
