#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# Asclepias Broker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

# TODO: Clean redis
invenio db destroy --yes-i-know
invenio db init create
invenio index destroy --yes-i-know --force
invenio index init --force

# Create admin user and role to restrict access
invenio users create admin@asclepias.org -a --password=123456
invenio roles create admin
invenio roles add admin@asclepias.org admin
invenio access allow superuser-access role admin
