#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# Asclepias Broker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

docker-compose  up -d

# TODO: Clean redis

invenio db destroy --yes-i-know
invenio db init create
curl -XDELETE localhost:9200/*
invenio index init --force

# Create admin role to rectict access
invenio users create test@test.ch -a --password=123456
invenio users create admin@test.ch -a --password=123456
invenio roles create admin
invenio roles add admin@test.ch admin
invenio access allow superuser-access role admin
